// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.12
// source: proto/beef.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeefRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BeefRequest) Reset() {
	*x = BeefRequest{}
	mi := &file_proto_beef_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeefRequest) ProtoMessage() {}

func (x *BeefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beef_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeefRequest.ProtoReflect.Descriptor instead.
func (*BeefRequest) Descriptor() ([]byte, []int) {
	return file_proto_beef_proto_rawDescGZIP(), []int{0}
}

type BeefResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beef map[string]int32 `protobuf:"bytes,1,rep,name=beef,proto3" json:"beef,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *BeefResponse) Reset() {
	*x = BeefResponse{}
	mi := &file_proto_beef_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeefResponse) ProtoMessage() {}

func (x *BeefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_beef_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeefResponse.ProtoReflect.Descriptor instead.
func (*BeefResponse) Descriptor() ([]byte, []int) {
	return file_proto_beef_proto_rawDescGZIP(), []int{1}
}

func (x *BeefResponse) GetBeef() map[string]int32 {
	if x != nil {
		return x.Beef
	}
	return nil
}

var File_proto_beef_proto protoreflect.FileDescriptor

var file_proto_beef_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x65, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x0d, 0x0a, 0x0b,
	0x42, 0x65, 0x65, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x7d, 0x0a, 0x0c, 0x42,
	0x65, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x62,
	0x65, 0x65, 0x66, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x42, 0x65, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x42, 0x65, 0x65, 0x66, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x62, 0x65, 0x65,
	0x66, 0x1a, 0x37, 0x0a, 0x09, 0x42, 0x65, 0x65, 0x66, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x47, 0x0a, 0x0b, 0x42, 0x65,
	0x65, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x42, 0x65, 0x65, 0x66, 0x12, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x42, 0x65, 0x65, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x42, 0x65, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_beef_proto_rawDescOnce sync.Once
	file_proto_beef_proto_rawDescData = file_proto_beef_proto_rawDesc
)

func file_proto_beef_proto_rawDescGZIP() []byte {
	file_proto_beef_proto_rawDescOnce.Do(func() {
		file_proto_beef_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_beef_proto_rawDescData)
	})
	return file_proto_beef_proto_rawDescData
}

var file_proto_beef_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_beef_proto_goTypes = []any{
	(*BeefRequest)(nil),  // 0: services.BeefRequest
	(*BeefResponse)(nil), // 1: services.BeefResponse
	nil,                  // 2: services.BeefResponse.BeefEntry
}
var file_proto_beef_proto_depIdxs = []int32{
	2, // 0: services.BeefResponse.beef:type_name -> services.BeefResponse.BeefEntry
	0, // 1: services.BeefService.GetBeef:input_type -> services.BeefRequest
	1, // 2: services.BeefService.GetBeef:output_type -> services.BeefResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_beef_proto_init() }
func file_proto_beef_proto_init() {
	if File_proto_beef_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_beef_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_beef_proto_goTypes,
		DependencyIndexes: file_proto_beef_proto_depIdxs,
		MessageInfos:      file_proto_beef_proto_msgTypes,
	}.Build()
	File_proto_beef_proto = out.File
	file_proto_beef_proto_rawDesc = nil
	file_proto_beef_proto_goTypes = nil
	file_proto_beef_proto_depIdxs = nil
}
